### PR TITLE
added 'template' keyword

### PR DESCRIPTION
**Pull request by azurepine**
Fix for the issue https://github.com/fnc12/sqlite_orm/issues/562

### CODE REVIEW

**Comment by fnc12** [comment]
@azurepine you need to modify files in `dev` folder not `sqlite_orm`. Then call python script to generate `sqlite_orm.h` like this:
```
python third_party/amalgamate/amalgamate.py -c third_party/amalgamate/config.json -s .
```
from repo root folder. Next commit it. Thanks

**Comment by azurepine** [comment]
Oops, there's an error with clang-format lint.
Is there something that I missed?

**Comment by fnc12** [comment]
Probably. Run formatter after generating `sqlite_orm` like this:
```
clang-format -i -style=file include/sqlite_orm/*.h tests/*.cpp tests/*/*.cpp dev/*.h tests/*/*.h examples/*.cpp
```
thanks

**Comment by fnc12** [comment]
I am sorry I did not add some instructions for contributors. I shall add them soon. If you don't have time to fix this PR I can make my own with the same fix.

**Comment by azurepine** [comment]
That's nice. 
It would be better to close this PR.

**Comment by fnc12** [comment]
@azurepine clang-format went well. What failed is windows build (all configurations). Please check out the error https://ci.appveyor.com/project/fnc12/sqlite-orm/builds/34283560/job/y6olx6s8794ms2to . Are you sure that this fix makes code better? And what compiler do you use?

**Comment by fnc12** [comment]
All linux build failed too https://travis-ci.org/github/fnc12/sqlite_orm/builds/711460864. I cannot merge while code cannot compile. Please fix it.

**Comment by azurepine** [comment]
I think it's kind of an amalgamation issue.
* These are what I've done.
  * I've modified "dev/column.h"
replaced `constraints::constraints_size<Op...>::value` 
with `constraints::template constraints_size<Op...>::value`

  * Then I've run the amalgamate.py script and clang-format that you told me.
  ```bash
  python third_party/amalgamate/amalgamate.py -c third_party/amalgamate/config.json -s .
  clang-format -i -style=file include/sqlite_orm/*.h
  ```

**Pull request closed without merging**
