### PR TITLE
Updated sync_schema return values

### PR DESCRIPTION
**Pull request by Ninja-007**
Updated sync_schema return values

### CODE REVIEW

**Comment by fnc12** [comment]
`sync_schema_result` and `sync_schema_status` have the same meaning. Let's remove `sync_schema_status` and replace it with `sync_schema_result`

**Comment by Ninja-007** [comment]
ok. Can you please make syny_schema_status publically available?

**Comment by fnc12** [comment]
it's already public isn't it?

**Comment by Ninja-007** [comment]
Yes, it is.

**Comment by fnc12** [comment]
Why are you asking me to make it public if it is already public?

**Comment by Ninja-007** [comment]
The separation between impl and public Storage class does confuse me sometimes. Sorry.

**Comment by Ninja-007** [comment]
There is a difference between sync_schema_result and sync_schema_status. sync_schema_status tells that what should be done and sync_schema_result what is done.

**Comment by fnc12** [comment]
@Ninja-007 yes but enum values maps to each other easily. It's better to write to docs that `schema_status` returns the same that `sync_schema` returns for concrete table but affects nothing

**Comment by Ninja-007** [comment]
Ok, I leave it upto you.

**Pull request merged**
