### PR TITLE
add `integrity_check` PRAGMA

### PR DESCRIPTION
**Pull request by mishal23**
Fixes: #731

### CODE REVIEW

**Comment by mishal23** [comment]
Hi @fnc12, can we merge this if everything is fine?

**Comment by fnc12** [comment]
@mishal23 merged. Sorry for long time waiting. I was a a little bit busy and forgot about this PR totally

**Comment by mishal23** [comment]
No issues! thanks a lot @fnc12 .

I had two questions regarding the dev branch & release process: 

1) is their a plan to merge dev branch later to master branch or dev branch is the main branch?
2) is their a plan for a release in nearby and the features that are planned for the release?

**Comment by fnc12** [comment]
1. `dev` branch is merged into `master` right before release
2. I cannot tell you exact date for next release. There is not a lot of features to publish right now so we need to implement more of them firstly. Planned features can be inspected in the [todo list](https://github.com/fnc12/sqlite_orm/blob/master/TODO.md) and issues with `feature` tag.

**Comment by mishal23** [comment]
Ok, got it. Thanks again.

**Comment by fnc12** [comment]
thanks to you!

**Comment by fnc12** [comment]
@mishal23 I've added `sync_schema` call here https://github.com/fnc12/sqlite_orm/pull/735 if you don't mind cause tests run fails without it on my mac

**Comment by mishal23** [comment]
Oh, yeah sure. Sorry, I forgot about `sync_schema` while adding the test.

**Pull request merged**
