### PR TITLE
CMake for examples and tests.

### PR DESCRIPTION
**Pull request by DerShokus**

### CODE REVIEW

**Comment by DerShokus** [comment]
`left_and_inner_join` fails. It wasn't called in the .travis.yml. Should it be excluded from the script?

**Comment by fnc12** [comment]
@DerShokus yes it should

**Comment by DerShokus** [comment]
@fnc12 fixed

**Comment by fnc12** [comment]
Thanks. CMake is what I've been missing

**Comment by fnc12** [comment]
@DerShokus can you please fix `#include <codecvt>` missing error form here https://travis-ci.org/fnc12/sqlite_orm ? Looks like we need to change compiler or std lib from gcc to clang in CI. Thanks

**Pull request merged**
