### PR TITLE
added pp verion check

### PR DESCRIPTION
**Pull request by Ninja-007**

### CODE REVIEW

**Comment by fnc12** [comment]
`>=` not `>`

**Comment by fnc12** [comment]
let's wait for travis and of everything is ok I'll merge it and uncomment `char()` function and add version check for it too

**Comment by fnc12** [comment]
please run tests before commiting (tests.cpp). You can also have different targets in your IDE for every example (like I do in Xcode). BTW that's your IDE?

**Comment by Ninja-007** [comment]
QtCreater.

**Pull request merged**
