### PR TITLE
first implementation of sql_auditing

### PR DESCRIPTION
**Pull request by juandent**

### CODE REVIEW

**Comment by juandent** [comment]
I don't know what went wrong with formatting

**Comment by fnc12** [comment]
@juandent probably clang-format version is incorrect (use 17) but maybe something else. I can't say cause I it happened on your machine and you have to fix it no matter the reason

**Comment by fnc12** [comment]
@juandent you need to fix formatting

**Comment by juandent** [comment]
> @juandent you need to fix formatting

the error seems to be in .clang-format file
can you send me this file?

**Comment by fnc12** [comment]
@juandent the error is not in `clang-format` file cause all other PR creator have it working. The file is located in repo root

**Pull request closed without merging**
