### PR TITLE
Issues/asterisk defined column order

### PR DESCRIPTION
**Pull request by trueqbit**
Addresses #1041.

`object<T>()` and `asterisk<T>()` now accept a `definedOrder` bool value, e.g.:

In pseudo code:
```
select(asterisk<User>()) -> SELECT * from User
select(asterisk<User>(false)) -> SELECT * from User
select(asterisk<User>(true))  -> SELECT id, name from User
```

The default is to use really an asterisk just like before.

### CODE REVIEW

**Comment by fnc12** [comment]
I thought it will accept `bool` values instead

**Comment by trueqbit** [comment]
> I thought it will accept `bool` values instead

In Slack you mentioned

> But we can think whether there will be more options in future. Cause if more than two options occur then we will need to refactor bool to enum and better make it using enum initially

Because the argument belongs to the public interface, we should make a good choice....
Since we don't know what the future holds, and since a simple boolean value can easily be overloaded, should we choose a simple bool now?

**Comment by fnc12** [comment]
it sounds reasonable. But please let's keeps as simple as we can. Example is `sync_schema`. It exists more than 5 years and still accepts `bool` with no problems. I offer you to add an overload with `enum` once new options appear but for now make it with `bool`.

**Review by fnc12 — CHANGES_REQUESTED** [review]

**Review by fnc12 — APPROVED** [review]

**Comment by fnc12** [comment]
thanks @trueqbit

**Pull request merged**
