### PR TITLE
New unsigned datatypes, Removed  std::to_string

### PR DESCRIPTION
**Pull request by Ninja-007**
Removed std::to_string usage
Added unsigned char
Added signed char
Added unsigned short int
Added unsigned int
Removed const return types to avoid complier warnings

### CODE REVIEW

**Comment by fnc12** [comment]
why did you removed `const` from `const bool operator==(const iterator_t &other) const`? It is recommended to add const to make statements like this `(it1 == it2) = it3;` unavailable

**Comment by Ninja-007** [comment]
I was getting complier warning. 

sqlite_orm.h:2651: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
                 const bool operator==(const iterator_t &other) const {
                                                               
gcc (GCC) 6.2.1 20160916 (Red Hat 6.2.1-3)

**Comment by fnc12** [comment]
Ok. Thanks you very much. I accept your pull request and remove `cout`s at all in the next commit.

**Comment by Ninja-007** [comment]
Thanks. :)

**Pull request merged**
