### PR TITLE
removed Complier warnings and unused headers

### PR DESCRIPTION
**Pull request by Ninja-007**
-Removed functional & iostream
-Initiated super class before member variables
-Comparision between signed and unsigned

### CODE REVIEW

**Comment by Ninja-007** [comment]
Sorry, I saw little confused. My fork was not in sync with you. I deleted my repo and reforked again. I hope, it has no conflicts now.

**Comment by fnc12** [comment]
it's ok. Thanks. One thing: `<functional>` is required for `std::function`. I'll fix it now

**Comment by Ninja-007** [comment]
Sorry for that. I did not get any complier error and CI was also successful.

**Comment by fnc12** [comment]
@Ninja-007 that's because of std lib implementation - one of the other headers already includes `<functional>` but we can't lean on it - in different std lib implementation it can be missing (GNU version of std lib)

**Pull request merged**
