### PR TITLE
Avoid foreign and/or references to be understand as SQLite command

### PR DESCRIPTION
**Pull request by indoubtchoose12**
in order to fix issue #462

### CODE REVIEW

**Comment by fnc12** [comment]
Please fix unit tests errors https://travis-ci.org/fnc12/sqlite_orm/builds/650510643

**Comment by fnc12** [comment]
There are serializator tests that failed. I've added them in this version. You need to add quotes to fix unit tests or I can do this

**Comment by indoubtchoose12** [comment]
Ok i'll fix the tests

**Comment by fnc12** [comment]
merged. Thank you!

**Pull request merged**
