### PR TITLE
Add Quick Check Pragma Option

### PR DESCRIPTION
**Pull request by jakemumu**
## What does this change?

Adds the quick check pragma command

## Why are you changing that?

I need to detect if databases are corrupted, but I don't need the verboseness or performance hits of the `integrity_check` 

## How do you manually test this?

Running `->pragma.quick_check` returns the results of a quick_check

### CODE REVIEW

**Comment by fnc12** [comment]
@jakemumu thanks for the PR. Please change the target from `master` to `dev`.

**Comment by fnc12** [comment]
@jakemumu thanks. Looks like the error can be fixed if you merge `dev` into your branch

**Comment by jakemumu** [comment]
@fnc12 done!

**Comment by fnc12** [comment]
@jakemumu thanks!

**Comment by trueqbit** [comment]
@jakemumu @fnc12 Unit tests are missing!

**Comment by jakemumu** [comment]
@trueqbit -- will give it a shot!

**Comment by jakemumu** [comment]
@trueqbit @fnc12 -- I've made a test for the quick check, but I see the test suit uses the amalgamated header which I'm unsure how to generate, is there docs on how to create it somewhere? 

Thanks! Sorry about that!

**Comment by trueqbit** [comment]
No worries 😃  Let's follow up in PR #1291.

**Comment by fnc12** [comment]
> @jakemumu @fnc12 Unit tests are missing!

Damn. My fault. Also I forgot to ask for amalgamation generation. Kurwa

**Pull request merged**
