### PR TITLE
added clang-format

### PR DESCRIPTION
**Pull request by DoozyX**
Added clang-format that I tried to match to your style but not all styles could be the same. I also applied the style formatting to all files that can be done with the following command: `find -name '*.cpp' -o -name '*.h' | xargs clang-format -i`
All the style options can be found on https://clang.llvm.org/docs/ClangFormatStyleOptions.html
You can replace the style with some already predefined styles as used for LLVM, Google, Chromium, Mozilla, WebKit with `clang-format -style=llvm -dump-config > .clang-format` as described in https://clang.llvm.org/docs/ClangFormat.html and then format the code again for all files.
Usually, most editors offer format on save or similar so everyone can use the same style without the need for manual checking.

### CODE REVIEW

**Comment by fnc12** [comment]
Thank you. Review will be long ~~and full of terrors~~. Also it would be great to add a configuration on CI for checking whether all files reminded in diff are formatted well. Can clang format perform this check?
P.S. I shall merge it once I finish my review

**Comment by DoozyX** [comment]
Do you want CI to fail if it is not formatted correctly only? I think it's not possible by clang-format itself but there are some cmake or python scripts that can use clang-format to check if the formatting is correct.

**Comment by fnc12** [comment]
I think I know how to check whether code is formatted well in a PR. Make a script with code format and `get status` further check

**Comment by DoozyX** [comment]
I think one option is with CMake, example script is here 
https://github.com/ttroy50/cmake-examples/tree/master/04-static-analysis/clang-format
another option is 
https://github.com/Sarcasm/run-clang-format
If you want I can integrate one of those

**Comment by fnc12** [comment]
@DoozyX  Yeah it would be great if yon integrate this. Thank you!

**Pull request merged**
