### PR TITLE
1.4

### PR DESCRIPTION
**Pull request by fnc12**

### CODE REVIEW

**Comment by sakethrampotturi** [comment]
This version fixes a couple of issues I'm seeing. When will this be available?

**Comment by fnc12** [comment]
I want to merge one feature more. Is it critical for you to get the update ASAP?

**Comment by fnc12** [comment]
Ok, I shall try to merge it in a week

**Comment by sakethrampotturi** [comment]
No issues, go for it. It's not required ASAP for me. A couple of weeks here and there should be okay 👍

**Pull request merged**
