### PR TITLE
fixed replace with private class members and added unit tests

### PR DESCRIPTION
**Pull request by fnc12**

### CODE REVIEW

**Comment by soroshsabz** [comment]
@fnc12 you want to decline my PR?

**Comment by soroshsabz** [comment]
@fnc12 It is not different to my PR in replace case (instead of I some refactoring to reduce code duplication)

But I want to resolve another problem in `get_object_field_pointer` in `insert` function that you say I break backward compatibility

**Comment by fnc12** [comment]
I just wanted to fix replace bug as it reported in the issue

**Comment by fnc12** [comment]
...I could not accept your fix cause it breaks `std::unique_ptr` field types

**Comment by soroshsabz** [comment]
> ...I could not accept your fix cause it breaks std::unique_ptr field types

...

I change my PR to only refactor please review it

thanks

**Pull request merged**
