### PR TITLE
added drone yml

### PR DESCRIPTION
**Pull request by fnc12**

### CODE REVIEW

**Comment by fnc12** [comment]
1. Just used the first example I met
2. Sure it does
3. I don't have XP in cmake
4. No, it is just a scratch that I created before I went to bed
5. ARM architecture

**Comment by soroshsabz** [comment]
@fnc12 you just need install cmake in drone.yaml and use it like https://github.com/fnc12/sqlite_orm/blob/dev/.travis.yml 

you just drop matrix and implement simple pipeline with some stage :)

**Comment by soroshsabz** [comment]
@fnc12 As you can see in this blog https://stefanscherer.github.io/use-appveyor-to-build-multi-arch-docker-image/ writer says appveyor and travis support ARM architecture

**Comment by fnc12** [comment]
@soroshsabz I did not know. Thank you

**Comment by fnc12** [comment]
The blog says only about AppVeyor not travis. Also travis has nothing about architecture in [docs](https://docs.travis-ci.com/user/reference/overview/)

**Pull request closed without merging**
