### PR TITLE
Updated result values of sync_schema

### PR DESCRIPTION
**Pull request by Ninja-007**
Updated result values of sync_schema

### CODE REVIEW

**Comment by fnc12** [comment]
why do you change enum names? There is no need

**Comment by Ninja-007** [comment]
I made them more descriptive.

**Comment by Ninja-007** [comment]
Well, it is clear for you. But for users of library who are not deep in the library code. It is hard understand short enum values. It will be great if you keep it.

**Comment by fnc12** [comment]
1) `tbl` is uncomfortable short version for eyes.
2) `new_columns_added` is not correct cause it can be returned in case if columns deleted 
3) `already_in_sync` and `synced` has same meaning but `already_in_sync` has more chars - not good
4) dropped_and_recreated is ok

**Comment by Ninja-007** [comment]
Thanks
1. tbl can be renamed to table.
2. I believe in case of deletion of excess columns. It will go to                 if(!gottaCreateTable){  //  if all storage columns are equal to actual db columns but there are excess columns at the db..
                    if(dbTableInfo.size() > 0){
                        //extra table columns than storage columns
                        _**if(!preserve){
                            gottaCreateTable = true;
                        }else{                           
                            backup_table(db);
                        }**_
                    }
                }
                if(gottaCreateTable){
                    this->drop_table(this->table.name, db);
                    this->create_table(db, this->table.name);
                    res = decltype(res)::dropped_and_recreated;
                }
3. After calling sync_schema, storage and table has to be "synced". "already_in_sync" indicates that nothing is done in the function because nothing is needed.
4. Thanks.

**Comment by fnc12** [comment]
1. ok
2. you're right but only if `preserve` is `false`. Otherwise `backup_table` fires and `res` is assigned with `columns_changed` (check latest commit - I've fixed it)
3. Just a naming problem. For me it is like iPhone syncing with iTunes - it syncs every time but if it was synced before that it is synced now. Thanks why enum values is called `synced`. But ok - we can change it to `already_in_sync` (don't forget to change `operator<<` with it)

**Comment by Ninja-007** [comment]
Thanks,
I removed << operator

**Pull request closed without merging**
