### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by Leon0402**
Some initial work to fix the errors, wip.

### CODE REVIEW

**Comment by Leon0402** [comment]
Have a look at https://travis-ci.community/t/travis-ci-build-no-longer-showing-as-check-on-github-pull-request-page/6955/10, this might give you hint how to enable travis gain?

Sometold told me you need to register to the beta version?

**Comment by Leon0402** [comment]
And you pipeline need ages, you really should kick out some configuration or fasten that up somehow ;)

**Comment by fnc12** [comment]
I shall paste here travis  build links https://travis-ci.org/github/fnc12/sqlite_orm/builds/716067194 until it is visible. Thanks for helping in fixing its visibility. Travis works, it starts build right after you create a PR but it does not show up. I shall read the link you provided

**Comment by fnc12** [comment]
I've check out travis web site profile settings and migrated this repo to beta. From now next commit must show up here.

**Comment by Leon0402** [comment]
I fixed the issues and did a little bit of clean up. Should be ready to merge.

**Comment by fnc12** [comment]
@Leon0402 man you're the greatest! One question: why did you remove `amalgamate` folder? It is required to build single header.

**Comment by Leon0402** [comment]
It made some issues as the hash has to be regularly updated and it wasn't in use anymore as far as I could see. Was I wrong about it? 

Usually sqlite3 is something you would require the user to have installed it on the system, the lib here will search for it. It might only be necessary to add such a script for CI, but as vcpkg is used, there is no need for it.

**Comment by Leon0402** [comment]
Ah I just saw that the ammagedon folder is for the lib itself and not only for the sqlite3, right? In this case I would rather remove the sqlite3 script, so make it mandatory to install sqlite3 on the system. Would that be okay?

**Comment by fnc12** [comment]
@Leon0402 amalgamate is used to construct single header from `dev` folder. The same is used in [nlohmann/json lib](https://github.com/nlohmann/json/tree/develop/third_party/amalgamate).

**Comment by Leon0402** [comment]
Sorry, completly confused :D 

I didn't meant to remove that. There are just multiple folders named "third_party" so I got confused I guess. Didn't meant to remove that.

**Comment by Leon0402** [comment]
I reverted that change and deleted the folder I meant to delete (which is the sqlite3 folder in test). Hope that's okay and the CI is still sucesssful ;)

**Comment by fnc12** [comment]
@Leon0402 nice thanks. I shall merge it once all builds are ready

**Comment by Leon0402** [comment]
Btw. have you thought about removing some configs from the CI? It really take ages and I'm not sure if it adds so much value to test with gcc7 and gcc9 for instance. Also it might be worth to drop x86 CI for Windows.
Just some recommendations though ... currently the CI needs an hour I think, which is really long (and made it a pain in the ass to actually fix the issues here)

**Comment by Leon0402** [comment]
> @Leon0402 nice thanks. I shall merge it once all builds are ready

Make sure to squash it, there are quite a lot "debug" commits here and other stuff. Just one commit would be more than enough for the changes I guess

**Comment by fnc12** [comment]
@Leon0402 or man I forgot to squash it. Make a PR again please

**Comment by Leon0402** [comment]
I'm not sure how, it says "fnc12:dev is up to date with all commits from Leon0402:fix/travis"

**Comment by fnc12** [comment]
@Leon0402 please repeat it - I've deleted those commits

**Pull request merged**
