### PR TITLE
Bugfix/1168

### PR DESCRIPTION
**Pull request by fnc12**
Fixing https://github.com/fnc12/sqlite_orm/issues/1168

### CODE REVIEW

**Review by trueqbit — APPROVED** [review]
Argh, stupid mistake!

I suggest we use the same C string literal `"SELECT name FROM sqlite_master WHERE type='table'"` as in [`storage_base::table_names()`](https://github.com/fnc12/sqlite_orm/blob/40dbec226b341c74fa4746e1af89f3344440b8ab/dev/storage_base.h#L192) below in order to benefit from string pooling.

**Comment by fnc12** [comment]
@trueqbit well it is not yours it is mine cause all you did is refactored existing quotes

**Comment by trueqbit** [comment]
> @trueqbit well it is not yours it is mine cause all you did is refactored existing quotes

I have to disappoint you - it was my mistake 🤣, see [#d470ca12b062](fnc12/sqlite_orm/commit/d470ca12b06263c05db4427a04cb1e127aa9f171#diff-fd236f159f27d3f53c594c14bc53feb7aaeaf21ca4dbe68bbf7ff09d06c63162)

**Comment by fnc12** [comment]
> > @trueqbit well it is not yours it is mine cause all you did is refactored existing quotes
> 
> I have to disappoint you - it was my mistake 🤣, see [#d470ca12b062](fnc12/sqlite_orm/commit/d470ca12b06263c05db4427a04cb1e127aa9f171#diff-fd236f159f27d3f53c594c14bc53feb7aaeaf21ca4dbe68bbf7ff09d06c63162)

it shows me 404. Even if it is made by you - no problem.

**Pull request merged**
